import * as keys from '#🪕/input/keys';
import { describe, expect, it } from 'vitest';

// #region Letters
const $aA = { code: 'KeyA' };
const $a = { code: 'KeyA', key: 'a' };
const $A = { code: 'KeyA', key: 'A' };
const $bB = { code: 'KeyB' };
const $b = { code: 'KeyB', key: 'b' };
const $B = { code: 'KeyB', key: 'B' };
const $cC = { code: 'KeyC' };
const $c = { code: 'KeyC', key: 'c' };
const $C = { code: 'KeyC', key: 'C' };
const $dD = { code: 'KeyD' };
const $d = { code: 'KeyD', key: 'd' };
const $D = { code: 'KeyD', key: 'D' };
const $eE = { code: 'KeyE' };
const $e = { code: 'KeyE', key: 'e' };
const $E = { code: 'KeyE', key: 'E' };
const $fF = { code: 'KeyF' };
const $f = { code: 'KeyF', key: 'f' };
const $F = { code: 'KeyF', key: 'F' };
const $gG = { code: 'KeyG' };
const $g = { code: 'KeyG', key: 'g' };
const $G = { code: 'KeyG', key: 'G' };
const $hH = { code: 'KeyH' };
const $h = { code: 'KeyH', key: 'h' };
const $H = { code: 'KeyH', key: 'H' };
const $iI = { code: 'KeyI' };
const $i = { code: 'KeyI', key: 'i' };
const $I = { code: 'KeyI', key: 'I' };
const $jJ = { code: 'KeyJ' };
const $j = { code: 'KeyJ', key: 'j' };
const $J = { code: 'KeyJ', key: 'J' };
const $kK = { code: 'KeyK' };
const $k = { code: 'KeyK', key: 'k' };
const $K = { code: 'KeyK', key: 'K' };
const $lL = { code: 'KeyL' };
const $l = { code: 'KeyL', key: 'l' };
const $L = { code: 'KeyL', key: 'L' };
const $mM = { code: 'KeyM' };
const $m = { code: 'KeyM', key: 'm' };
const $M = { code: 'KeyM', key: 'M' };
const $nN = { code: 'KeyN' };
const $n = { code: 'KeyN', key: 'n' };
const $N = { code: 'KeyN', key: 'N' };
const $oO = { code: 'KeyO' };
const $o = { code: 'KeyO', key: 'o' };
const $O = { code: 'KeyO', key: 'O' };
const $pP = { code: 'KeyP' };
const $p = { code: 'KeyP', key: 'p' };
const $P = { code: 'KeyP', key: 'P' };
const $qQ = { code: 'KeyQ' };
const $q = { code: 'KeyQ', key: 'q' };
const $Q = { code: 'KeyQ', key: 'Q' };
const $rR = { code: 'KeyR' };
const $r = { code: 'KeyR', key: 'r' };
const $R = { code: 'KeyR', key: 'R' };
const $sS = { code: 'KeyS' };
const $s = { code: 'KeyS', key: 's' };
const $S = { code: 'KeyS', key: 'S' };
const $tT = { code: 'KeyT' };
const $t = { code: 'KeyT', key: 't' };
const $T = { code: 'KeyT', key: 'T' };
const $uU = { code: 'KeyU' };
const $u = { code: 'KeyU', key: 'u' };
const $U = { code: 'KeyU', key: 'U' };
const $vV = { code: 'KeyV' };
const $v = { code: 'KeyV', key: 'v' };
const $V = { code: 'KeyV', key: 'V' };
const $wW = { code: 'KeyW' };
const $w = { code: 'KeyW', key: 'w' };
const $W = { code: 'KeyW', key: 'W' };
const $xX = { code: 'KeyX' };
const $x = { code: 'KeyX', key: 'x' };
const $X = { code: 'KeyX', key: 'X' };
const $yY = { code: 'KeyY' };
const $y = { code: 'KeyY', key: 'y' };
const $Y = { code: 'KeyY', key: 'Y' };
const $zZ = { code: 'KeyZ' };
const $z = { code: 'KeyZ', key: 'z' };
const $Z = { code: 'KeyZ', key: 'Z' };
// #endregion Letters

// #region Misc keys
const $add = { key: '+' } as const;
const $alt = { key: 'Alt', altKey: true } as const;
const $backslash = { code: 'Backslash', key: '\\' } as const;
const $backspace = { code: 'Backspace', key: 'Backspace' } as const;
const $backtick = { code: 'Backquote', key: '`' } as const;
const $capsLock = { code: 'CapsLock', key: 'CapsLock' } as const;
const $colon = { code: 'Semicolon', key: ':', shiftKey: true } as const;
const $comma = { code: 'Comma', key: ',' } as const;
const $ctrl = { key: 'Control', ctrlKey: true } as const;
const $delete = { code: 'Delete', key: 'Delete' } as const;
const $divide = { key: '/' } as const;
const $doubleQuote = { code: 'Quote', key: '"', shiftKey: true } as const;
const $down = { code: 'ArrowDown', key: 'ArrowDown' } as const;
const $end = { code: 'End', key: 'End' } as const;
const $enter = { key: 'Enter' } as const;
const $esc = { code: 'Escape', key: 'Escape' } as const;
const $f1 = { code: 'F1', key: 'F1' } as const;
const $f2 = { code: 'F2', key: 'F2' } as const;
const $f3 = { code: 'F3', key: 'F3' } as const;
const $f4 = { code: 'F4', key: 'F4' } as const;
const $f5 = { code: 'F5', key: 'F5' } as const;
const $f6 = { code: 'F6', key: 'F6' } as const;
const $f7 = { code: 'F7', key: 'F7' } as const;
const $f8 = { code: 'F8', key: 'F8' } as const;
const $f9 = { code: 'F9', key: 'F9' } as const;
const $f10 = { code: 'F10', key: 'F10' } as const;
const $f11 = { code: 'F11', key: 'F11' } as const;
const $f12 = { code: 'F12', key: 'F12' } as const;
const $home = { code: 'Home', key: 'Home' } as const;
const $insert = { code: 'Insert', key: 'Insert' } as const;
const $left = { code: 'ArrowLeft', key: 'ArrowLeft' } as const;
const $leftAlt = { code: 'AltLeft', key: 'Alt', altKey: true } as const;
const $leftAngleBracket = { code: 'Comma', key: '<', shiftKey: true } as const;
const $leftBracket = { code: 'BracketLeft', key: '{', shiftKey: true } as const;
const $leftCtrl = { code: 'ControlLeft', key: 'Control', ctrlKey: true } as const;
const $leftMeta = { code: 'MetaLeft', key: 'Meta', metaKey: true } as const;
const $leftShift = { code: 'ShiftLeft', key: 'Shift', shiftKey: true } as const;
const $leftSquareBracket = { code: 'BracketLeft', key: '[' } as const;
const $meta = { key: 'Meta', metaKey: true } as const;
const $multiply = { key: '*' } as const;
const $pageDown = { code: 'PageDown', key: 'PageDown' } as const;
const $pageUp = { code: 'PageUp', key: 'PageUp' } as const;
const $period = { code: 'Period', key: '.' } as const;
const $pipe = { code: 'Backslash', key: '|', shiftKey: true } as const;
const $questionMark = { code: 'Slash', key: '?', shiftKey: true } as const;
const $return = { code: 'Enter', key: 'Enter' } as const;
const $right = { code: 'ArrowRight', key: 'ArrowRight' } as const;
const $rightAlt = { code: 'AltRight', key: 'Alt', altKey: true } as const;
const $rightAngleBracket = { code: 'Period', key: '>', shiftKey: true } as const;
const $rightBracket = { code: 'BracketRight', key: '}', shiftKey: true } as const;
const $rightCtrl = { code: 'ControlRight', key: 'Control', ctrlKey: true } as const;
const $rightMeta = { code: 'MetaRight', key: 'Meta', metaKey: true } as const;
const $rightShift = { code: 'ShiftRight', key: 'Shift', shiftKey: true } as const;
const $rightSquareBracket = { code: 'BracketRight', key: ']' } as const;
const $semicolon = { code: 'Semicolon', key: ';' } as const;
const $shift = { key: 'Shift', shiftKey: true } as const;
const $singleQuote = { code: 'Quote', key: "'" } as const;
const $slash = { code: 'Slash', key: '/' } as const;
const $subtract = { key: '-' } as const;
const $tab = { code: 'Tab', key: 'Tab' } as const;
const $tilde = { code: 'Backquote', key: '~', shiftKey: true } as const;
const $up = { code: 'ArrowUp', key: 'ArrowUp' } as const;
// #endregion Misc keys

// #region Numbers
const $0 = { key: '0' } as const;
const $1 = { key: '1' } as const;
const $2 = { key: '2' } as const;
const $3 = { key: '3' } as const;
const $4 = { key: '4' } as const;
const $5 = { key: '5' } as const;
const $6 = { key: '6' } as const;
const $7 = { key: '7' } as const;
const $8 = { key: '8' } as const;
const $9 = { key: '9' } as const;
const $ampersand = { code: 'Digit7', key: '&', shiftKey: true } as const;
const $asterisk = { code: 'Digit8', key: '*', shiftKey: true } as const;
const $at = { code: 'Digit2', key: '@', shiftKey: true } as const;
const $caret = { code: 'Digit6', key: '^', shiftKey: true } as const;
const $dash = { code: 'Minus', key: '-' } as const;
const $digit0 = { code: 'Digit0', key: '0' } as const;
const $digit1 = { code: 'Digit1', key: '1' } as const;
const $digit2 = { code: 'Digit2', key: '2' } as const;
const $digit3 = { code: 'Digit3', key: '3' } as const;
const $digit4 = { code: 'Digit4', key: '4' } as const;
const $digit5 = { code: 'Digit5', key: '5' } as const;
const $digit6 = { code: 'Digit6', key: '6' } as const;
const $digit7 = { code: 'Digit7', key: '7' } as const;
const $digit8 = { code: 'Digit8', key: '8' } as const;
const $digit9 = { code: 'Digit9', key: '9' } as const;
const $dollarSign = { code: 'Digit4', key: '$', shiftKey: true } as const;
const $equal = { code: 'Equal', key: '=' } as const;
const $exclamationMark = { code: 'Digit1', key: '!', shiftKey: true } as const;
const $hash = { code: 'Digit3', key: '#', shiftKey: true } as const;
const $leftParen = { code: 'Digit9', key: '(', shiftKey: true } as const;
const $numAdd = { code: 'NumpadAdd', key: '+' } as const;
const $numDecimal = { code: 'NumpadDecimal', key: '.' } as const;
const $numDivide = { code: 'NumpadDivide', key: '/' } as const;
const $numEnter = { code: 'NumpadEnter', key: 'Enter' } as const;
const $numLock = { code: 'NumLock', key: 'NumLock' } as const;
const $numMultiply = { code: 'NumpadMultiply', key: '*' } as const;
const $numSubtract = { code: 'NumpadSubtract', key: '-' } as const;
const $num0 = { code: 'Numpad0', key: '0' } as const;
const $num1 = { code: 'Numpad1', key: '1' } as const;
const $num2 = { code: 'Numpad2', key: '2' } as const;
const $num3 = { code: 'Numpad3', key: '3' } as const;
const $num4 = { code: 'Numpad4', key: '4' } as const;
const $num5 = { code: 'Numpad5', key: '5' } as const;
const $num6 = { code: 'Numpad6', key: '6' } as const;
const $num7 = { code: 'Numpad7', key: '7' } as const;
const $num8 = { code: 'Numpad8', key: '8' } as const;
const $num9 = { code: 'Numpad9', key: '9' } as const;
const $percentSign = { code: 'Digit5', key: '%', shiftKey: true } as const;
const $plus = { code: 'Equal', key: '+', shiftKey: true } as const;
const $rightParen = { code: 'Digit0', key: ')', shiftKey: true } as const;
const $row0 = { code: 'Digit0' } as const;
const $row1 = { code: 'Digit1' } as const;
const $row2 = { code: 'Digit2' } as const;
const $row3 = { code: 'Digit3' } as const;
const $row4 = { code: 'Digit4' } as const;
const $row5 = { code: 'Digit5' } as const;
const $row6 = { code: 'Digit6' } as const;
const $row7 = { code: 'Digit7' } as const;
const $row8 = { code: 'Digit8' } as const;
const $row9 = { code: 'Digit9' } as const;
const $underscore = { code: 'Minus', key: '_', shiftKey: true } as const;
// #endregion Numbers

describe('keys (module)', () => {
  describe('exported constants', () => {
    it('letters', () => {
      expect(keys.$aA).toEqual($aA);
      expect(keys.$a).toEqual($a);
      expect(keys.$A).toEqual($A);
      expect(keys.$bB).toEqual($bB);
      expect(keys.$b).toEqual($b);
      expect(keys.$B).toEqual($B);
      expect(keys.$cC).toEqual($cC);
      expect(keys.$c).toEqual($c);
      expect(keys.$C).toEqual($C);
      expect(keys.$dD).toEqual($dD);
      expect(keys.$d).toEqual($d);
      expect(keys.$D).toEqual($D);
      expect(keys.$eE).toEqual($eE);
      expect(keys.$e).toEqual($e);
      expect(keys.$E).toEqual($E);
      expect(keys.$fF).toEqual($fF);
      expect(keys.$f).toEqual($f);
      expect(keys.$F).toEqual($F);
      expect(keys.$gG).toEqual($gG);
      expect(keys.$g).toEqual($g);
      expect(keys.$G).toEqual($G);
      expect(keys.$hH).toEqual($hH);
      expect(keys.$h).toEqual($h);
      expect(keys.$H).toEqual($H);
      expect(keys.$iI).toEqual($iI);
      expect(keys.$i).toEqual($i);
      expect(keys.$I).toEqual($I);
      expect(keys.$jJ).toEqual($jJ);
      expect(keys.$j).toEqual($j);
      expect(keys.$J).toEqual($J);
      expect(keys.$kK).toEqual($kK);
      expect(keys.$k).toEqual($k);
      expect(keys.$K).toEqual($K);
      expect(keys.$lL).toEqual($lL);
      expect(keys.$l).toEqual($l);
      expect(keys.$L).toEqual($L);
      expect(keys.$mM).toEqual($mM);
      expect(keys.$m).toEqual($m);
      expect(keys.$M).toEqual($M);
      expect(keys.$nN).toEqual($nN);
      expect(keys.$n).toEqual($n);
      expect(keys.$N).toEqual($N);
      expect(keys.$oO).toEqual($oO);
      expect(keys.$o).toEqual($o);
      expect(keys.$O).toEqual($O);
      expect(keys.$pP).toEqual($pP);
      expect(keys.$p).toEqual($p);
      expect(keys.$P).toEqual($P);
      expect(keys.$qQ).toEqual($qQ);
      expect(keys.$q).toEqual($q);
      expect(keys.$Q).toEqual($Q);
      expect(keys.$rR).toEqual($rR);
      expect(keys.$r).toEqual($r);
      expect(keys.$R).toEqual($R);
      expect(keys.$sS).toEqual($sS);
      expect(keys.$s).toEqual($s);
      expect(keys.$S).toEqual($S);
      expect(keys.$tT).toEqual($tT);
      expect(keys.$t).toEqual($t);
      expect(keys.$T).toEqual($T);
      expect(keys.$uU).toEqual($uU);
      expect(keys.$u).toEqual($u);
      expect(keys.$U).toEqual($U);
      expect(keys.$vV).toEqual($vV);
      expect(keys.$v).toEqual($v);
      expect(keys.$V).toEqual($V);
      expect(keys.$wW).toEqual($wW);
      expect(keys.$w).toEqual($w);
      expect(keys.$W).toEqual($W);
      expect(keys.$xX).toEqual($xX);
      expect(keys.$x).toEqual($x);
      expect(keys.$X).toEqual($X);
      expect(keys.$yY).toEqual($yY);
      expect(keys.$y).toEqual($y);
      expect(keys.$Y).toEqual($Y);
      expect(keys.$zZ).toEqual($zZ);
      expect(keys.$z).toEqual($z);
      expect(keys.$Z).toEqual($Z);
    });

    it('misc keys', () => {
      expect(keys.$add).toEqual($add);
      expect(keys.$alt).toEqual($alt);
      expect(keys.$backslash).toEqual($backslash);
      expect(keys.$backspace).toEqual($backspace);
      expect(keys.$backtick).toEqual($backtick);
      expect(keys.$capsLock).toEqual($capsLock);
      expect(keys.$colon).toEqual($colon);
      expect(keys.$comma).toEqual($comma);
      expect(keys.$ctrl).toEqual($ctrl);
      expect(keys.$delete).toEqual($delete);
      expect(keys.$divide).toEqual($divide);
      expect(keys.$doubleQuote).toEqual($doubleQuote);
      expect(keys.$down).toEqual($down);
      expect(keys.$end).toEqual($end);
      expect(keys.$enter).toEqual($enter);
      expect(keys.$esc).toEqual($esc);
      expect(keys.$f1).toEqual($f1);
      expect(keys.$f2).toEqual($f2);
      expect(keys.$f3).toEqual($f3);
      expect(keys.$f4).toEqual($f4);
      expect(keys.$f5).toEqual($f5);
      expect(keys.$f6).toEqual($f6);
      expect(keys.$f7).toEqual($f7);
      expect(keys.$f8).toEqual($f8);
      expect(keys.$f9).toEqual($f9);
      expect(keys.$f10).toEqual($f10);
      expect(keys.$f11).toEqual($f11);
      expect(keys.$f12).toEqual($f12);
      expect(keys.$home).toEqual($home);
      expect(keys.$insert).toEqual($insert);
      expect(keys.$left).toEqual($left);
      expect(keys.$leftAlt).toEqual($leftAlt);
      expect(keys.$leftAngleBracket).toEqual($leftAngleBracket);
      expect(keys.$leftBracket).toEqual($leftBracket);
      expect(keys.$leftCtrl).toEqual($leftCtrl);
      expect(keys.$leftMeta).toEqual($leftMeta);
      expect(keys.$leftShift).toEqual($leftShift);
      expect(keys.$leftSquareBracket).toEqual($leftSquareBracket);
      expect(keys.$meta).toEqual($meta);
      expect(keys.$multiply).toEqual($multiply);
      expect(keys.$pageDown).toEqual($pageDown);
      expect(keys.$pageUp).toEqual($pageUp);
      expect(keys.$period).toEqual($period);
      expect(keys.$pipe).toEqual($pipe);
      expect(keys.$questionMark).toEqual($questionMark);
      expect(keys.$return).toEqual($return);
      expect(keys.$right).toEqual($right);
      expect(keys.$rightAlt).toEqual($rightAlt);
      expect(keys.$rightAngleBracket).toEqual($rightAngleBracket);
      expect(keys.$rightBracket).toEqual($rightBracket);
      expect(keys.$rightCtrl).toEqual($rightCtrl);
      expect(keys.$rightMeta).toEqual($rightMeta);
      expect(keys.$rightShift).toEqual($rightShift);
      expect(keys.$rightSquareBracket).toEqual($rightSquareBracket);
      expect(keys.$semicolon).toEqual($semicolon);
      expect(keys.$shift).toEqual($shift);
      expect(keys.$singleQuote).toEqual($singleQuote);
      expect(keys.$slash).toEqual($slash);
      expect(keys.$subtract).toEqual($subtract);
      expect(keys.$tab).toEqual($tab);
      expect(keys.$tilde).toEqual($tilde);
      expect(keys.$up).toEqual($up);
    });

    it('numbers', () => {
      expect(keys.$0).toEqual($0);
      expect(keys.$1).toEqual($1);
      expect(keys.$2).toEqual($2);
      expect(keys.$3).toEqual($3);
      expect(keys.$4).toEqual($4);
      expect(keys.$5).toEqual($5);
      expect(keys.$6).toEqual($6);
      expect(keys.$7).toEqual($7);
      expect(keys.$8).toEqual($8);
      expect(keys.$9).toEqual($9);
      expect(keys.$ampersand).toEqual($ampersand);
      expect(keys.$asterisk).toEqual($asterisk);
      expect(keys.$at).toEqual($at);
      expect(keys.$caret).toEqual($caret);
      expect(keys.$dash).toEqual($dash);
      expect(keys.$digit0).toEqual($digit0);
      expect(keys.$digit1).toEqual($digit1);
      expect(keys.$digit2).toEqual($digit2);
      expect(keys.$digit3).toEqual($digit3);
      expect(keys.$digit4).toEqual($digit4);
      expect(keys.$digit5).toEqual($digit5);
      expect(keys.$digit6).toEqual($digit6);
      expect(keys.$digit7).toEqual($digit7);
      expect(keys.$digit8).toEqual($digit8);
      expect(keys.$digit9).toEqual($digit9);
      expect(keys.$dollarSign).toEqual($dollarSign);
      expect(keys.$equal).toEqual($equal);
      expect(keys.$exclamationMark).toEqual($exclamationMark);
      expect(keys.$hash).toEqual($hash);
      expect(keys.$leftParen).toEqual($leftParen);
      expect(keys.$numAdd).toEqual($numAdd);
      expect(keys.$numDecimal).toEqual($numDecimal);
      expect(keys.$numDivide).toEqual($numDivide);
      expect(keys.$numEnter).toEqual($numEnter);
      expect(keys.$numLock).toEqual($numLock);
      expect(keys.$numMultiply).toEqual($numMultiply);
      expect(keys.$numSubtract).toEqual($numSubtract);
      expect(keys.$num0).toEqual($num0);
      expect(keys.$num1).toEqual($num1);
      expect(keys.$num2).toEqual($num2);
      expect(keys.$num3).toEqual($num3);
      expect(keys.$num4).toEqual($num4);
      expect(keys.$num5).toEqual($num5);
      expect(keys.$num6).toEqual($num6);
      expect(keys.$num7).toEqual($num7);
      expect(keys.$num8).toEqual($num8);
      expect(keys.$num9).toEqual($num9);
      expect(keys.$percentSign).toEqual($percentSign);
      expect(keys.$plus).toEqual($plus);
      expect(keys.$rightParen).toEqual($rightParen);
      expect(keys.$row0).toEqual($row0);
      expect(keys.$row1).toEqual($row1);
      expect(keys.$row2).toEqual($row2);
      expect(keys.$row3).toEqual($row3);
      expect(keys.$row4).toEqual($row4);
      expect(keys.$row5).toEqual($row5);
      expect(keys.$row6).toEqual($row6);
      expect(keys.$row7).toEqual($row7);
      expect(keys.$row8).toEqual($row8);
      expect(keys.$row9).toEqual($row9);
      expect(keys.$underscore).toEqual($underscore);
    });
  });

  describe('exported functions', () => {
    const base = { code: 'Enter' };
    it('addAlt()', () => {
      expect(keys.addAlt(base)).toEqual({ altKey: true, code: 'Enter' });
      expect(keys.addAlt(base, false)).toEqual({ altKey: false, code: 'Enter' });
    });

    it('addCtrl()', () => {
      expect(keys.addCtrl(base)).toEqual({ code: 'Enter', ctrlKey: true });
      expect(keys.addCtrl(base, false)).toEqual({ code: 'Enter', ctrlKey: false });
    });

    it('addMeta()', () => {
      expect(keys.addMeta(base)).toEqual({ code: 'Enter', metaKey: true });
      expect(keys.addMeta(base, false)).toEqual({ code: 'Enter', metaKey: false });
    });

    it('addShift()', () => {
      expect(keys.addShift(base)).toEqual({ code: 'Enter', shiftKey: true });
      expect(keys.addShift(base, false)).toEqual({ code: 'Enter', shiftKey: false });
    });
  });
});
